### PR TITLE
Add round icon support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gcantoni** [comment]
I don't think it's a good idea to implement. As i know Google is using round icon in AOSP but they forgot to change it for Nexus 5X/6P.

**Comment by folgore95** [comment]
Closed because round icons

**Comment by gcantoni** [comment]
OMS loads too late.

**Comment by ghost** [comment]
@folgore95 They didn't forgot, it's like a Pixel-exclusive feature which every OEM and developer can implement into their ROM.

**Comment by ghost** [comment]
@folgore95 Thank you anyway for trying this.

**Pull request closed without merging**
